name: Rust Linters

on:
  pull_request:
  push:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable

    - name: Install Rustfmt and Clippy
      run: rustup component add rustfmt clippy

    - name: Check code formatting
      run: cargo fmt -- --check

    - name: Run Clippy
      run: cargo clippy -- -D warnings
